[tool.poetry]
name = "isamples_client"
version = "0.1.0.post1"
description = "This is a Python wrapper for the iSamples API (documented at https://central.isample.xyz/isamples_central/docs)"
authors = ["Raymond Yee <raymond.yee@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
httpx = "*"
requests = "*"
pandas = "*"
xarray = "*"
pysolr = "*"
multidict = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"